spring.application.name=jobtrack

# ===============================

# DATABASE CONFIG (NEON)

# ===============================

spring.datasource.url=jdbc:postgresql://ep-billowing-math-a15zguev.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HS6EcWlnZf3k

# ===============================

# JPA / HIBERNATE CONFIG

# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional

spring.jpa.properties.hibernate.format_sql=true

===================================
# Disable Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
